---

- hosts: '{{robothosts}}'

  remote_user: ubuntu

  tasks:
    - set_fact:
        my_ssh_key: "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub"

    - authorized_key: user=ubuntu key="{{ lookup('file', my_ssh_key) }}"
      sudo: yes
