--- 
ubuntu_version: 16.04
pi_board: 3
robothost: ubuntu
robotuser: ubuntu
archive_base_url: http://www.finnie.org/software/raspberrypi/ubuntu-rpi3
archive_dest_path: "/tmp/{{ archive_name }}"
archive_name: "ubuntu-{{ ubuntu_version }}-preinstalled-server-armhf+raspi3.img.xz"
archive_type: xz
archive_url: "{{ archive_base_url }}/{{ archive_name }}"
imgname: "ubuntu-{{ ubuntu_version }}-preinstalled-server-armhf+raspi3.img"
