---

#placeholder until we get roles really....rolling
robothost: ubuntu
robotuser: ubuntu
zipfile: latest-ubiquity-trusty.zip
zippath: "/tmp/{{ zipfile }}"
zipurl: https://ubiquityrobotics.com
imgprefix: 2015-10-14-ubuntu-trusty
bmapname: "{{ imgprefix }}.bmap"
imgname: "{{ imgprefix }}.img"
