---
- hosts: "{{ robothost }}"
  
  vars:
    - robotuser: ubuntu
    - robotpw  : ubuntu
    - humanuser: ubuntu
    - robottype: notmagni
    - rosversion: indigo

  tasks:
    
    - set_fact:
        local_ssh_key: "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub"

    - authorized_key: user=ubuntu key="{{ lookup('file', local_ssh_key) }}"
      sudo: yes

    - name: ensure basic tools and packages are installed on remote host
      sudo: yes
      apt: name={{ item }} state=present update_cache=yes
      with_items:
         - curl
         - wget 
         - git
         - bmap-tools 
         - libnss-mdns
         - util-linux
         - chrony
         - ros-indigo-tf2-kdl
         - tzdata 
         - ros-indigo-roslint
         - dphys-swapfile
           
    - name: install Magni-related packages
      sudo: yes
      apt: name={{ item }} state=present 
      with_items:
         - ros-indigo-hardware-interface
         - ros-indigo-controller-manager 
      when: robottype == 'magni'

    - name: clone Magni-related repos 
      sudo: yes
      git: repo=https://github.com/UbiquityRobotics/ubiquity_motor.git dest=/home/'{{ robotuser }}'/catkin_ws/src clone=yes
      when: robottype == 'magni'

    - name: pull in robot-upstart
      sudo: yes
      git: repo=https://github.com/clearpathrobotics/robot_upstart.git dest=/home/'{{ robotuser }}'/catkin_ws/src clone=yes

    - name: Permissions fix-up
      sudo: yes 
      file: path=/home/{{robotuser}} owner={{robotuser}} group={{robotuser}} recurse=yes

    - name: ensure entry for iface lo
      sudo: yes
      lineinfile: dest=/etc/network/interfaces line="iface lo inet loopback"

    - name: ensure entry for eth0
      sudo: yes
      lineinfile: dest=/etc/network/interfaces line="allow-hotplug eth0"

    - name: ensure entry for iface eth0
      sudo: yes
      lineinfile: dest=/etc/network/interfaces line="iface eth0 inet dhcp"



    # Not sure why we want this on an sdcard
    #- name: Add dphys-swapfile
    #  sudo: yes
    #  apt: name=dphys-swapfile state=present
 
    - debug: msg="Done. Your Pi is ready to join the ROS Robot Revolution! "
    - debug: msg="You will need to set up wireless networking manually based on your current environment"
    - debug: msg="For next steps, check out the tutorials at http://www.ros.org or other playbooks for the turtlebot or BotVac80(bv80)"
    
